import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from './layout.module.scss';
import Sidebar from "@/components/sidebar";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Zing mp3 clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.wrapper}>
          <Sidebar/>
          <div className="">
            <Header/>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
